name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1
  ACTIONS_CACHE_SEGMENT_SIZE: 64000000 # 64MB segments
  ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ACTIONS_CACHE_URL: ${{ secrets.ACTIONS_CACHE_URL }}
  ZSTD_CLEVEL: 1

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup dependency caching
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/pnpm/store
            ~/.cache/pnpm
            node_modules
            apps/*/node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run format check
        run: pnpm format

      - name: Run linting
        run: pnpm eslint

      - name: Run type checking
        run: pnpm tsc

      - name: Run tests
        run: pnpm test

      - name: Run build
        if: github.ref == 'refs/heads/main'
        run: pnpm build

      - name: Deploy Storybook to Firebase
        if: github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AI_AGENT_TRACE_UI }}"
          projectId: agent-prism-ui
          channelId: live
